# Generated by Django 2.2.5 on 2021-08-22 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_twinkle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bands.Band'),
        ),
    ]
