# Generated by Django 2.2.5 on 2021-07-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210729_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schoolEmail',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address 2nd'),
        ),
    ]
