# Generated by Django 2.2.5 on 2021-11-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211113_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school_email_confirmed',
            new_name='school_email_verified',
        ),
    ]
