# Generated by Django 2.2.5 on 2021-11-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211116_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='schoolEmail',
            new_name='school_email',
        ),
    ]
