# Generated by Django 2.2.5 on 2021-11-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211116_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_2nd',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_2nd_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='school email adress'),
        ),
    ]
