# Generated by Django 2.2.5 on 2021-11-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211116_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email adress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_2nd',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address for second'),
        ),
    ]
