# Generated by Django 2.2.5 on 2022-04-26 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schoolposts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KaistPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Post')),
            ],
            options={
                'abstract': False,
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('kaistpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolposts.KaistPost')),
            ],
            options={
                'abstract': False,
            },
            bases=('schoolposts.kaistpost',),
        ),
        migrations.CreateModel(
            name='Dorms',
            fields=[
                ('kaistpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolposts.KaistPost')),
            ],
            options={
                'abstract': False,
            },
            bases=('schoolposts.kaistpost',),
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('kaistpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolposts.KaistPost')),
            ],
            options={
                'abstract': False,
            },
            bases=('schoolposts.kaistpost',),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('kaistpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolposts.KaistPost')),
            ],
            options={
                'abstract': False,
            },
            bases=('schoolposts.kaistpost',),
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('kaistpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolposts.KaistPost')),
            ],
            options={
                'abstract': False,
            },
            bases=('schoolposts.kaistpost',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=schoolposts.models.get_image_filename, verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schoolposts.Post')),
            ],
        ),
    ]
