# Generated by Django 2.2.5 on 2021-08-04 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Band Member',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('official', models.BooleanField(default=False)),
                ('grouptype', models.CharField(choices=[('학교행정', '학교행정'), ('과목', '과목'), ('동아리', '동아리')], max_length=20, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('mainfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('bannerfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('chairperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band_chairman', to=settings.AUTH_USER_MODEL)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.BandMember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
