# Generated by Django 2.2.5 on 2021-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='grouptype',
            field=models.CharField(choices=[('학교행정', '학교행정'), ('과목', '과목'), ('동아리', '동아리'), ('동아리', '기타')], max_length=20, null=True),
        ),
    ]
