# Generated by Django 2.2.5 on 2021-08-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20210805_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='grouptype',
            field=models.CharField(choices=[('학교행정', '학교행정'), ('과목', '과목'), ('동아리', '동아리'), ('동아리', '기타'), ('IOSTAR OFFICIAL', '아이오스타 오피셜')], max_length=20, null=True),
        ),
    ]
