# Generated by Django 2.2.5 on 2022-02-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iostream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iostream',
            name='file',
            field=models.ImageField(blank='True', null='True', upload_to='uploads/iostream'),
            preserve_default='True',
        ),
    ]
