# Generated by Django 2.2.5 on 2022-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iostream', '0002_iostream_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iostream',
            name='file',
            field=models.ImageField(blank='True', null='True', upload_to='uploads/iostreamç'),
        ),
    ]
