# Generated by Django 2.2.5 on 2022-06-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iostream', '0004_auto_20220604_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iostream',
            name='file',
            field=models.ImageField(blank='True', null='True', upload_to='uploads/iostreamç'),
        ),
        migrations.AlterField(
            model_name='iostream',
            name='reply_to',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='iostream.Iostream'),
        ),
    ]
